import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense, lazy, useState } from "react";
import dynamic from "next/dynamic";
import { Button, Drawer } from "antd";
import { useDispatch } from "react-redux";
import { useSelector } from "react-redux";

const ProductList = lazy(() => import("remote/ProductList", { ssr: false }));
const CartList = dynamic(() => import("basket/Cart"), { ssr: false });
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const dispatch = useDispatch(); // Use dispatch to dispatch actions
  const visible = useSelector((state) => state.drawer.visible);
  const onClose = () => {
    dispatch({ type: 'drawer/closeDrawer' })
  };

  return (
    <>
      <Head>
        <title>Host Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${geistSans.variable} ${geistMono.variable}`}>
        <ProductList />
        {/* Drawer component */}
        <Drawer
          title="Your Cart"
          placement="right"
          width={600}
          onClose={onClose}
          visible={visible}
        >
          <Suspense fallback="Loading Cart...">
            <CartList /> {/* Cart content goes here */}
          </Suspense>
        </Drawer>
      </div>
    </>
  );
}
