import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense, lazy } from "react";
import dynamic from "next/dynamic";
const ProductList = lazy(() => import("remote/ProductList", { ssr: false }));
const CartList = dynamic(() => import("basket/Cart"), { ssr: false });
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Host Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={` ${geistSans.variable} ${geistMono.variable}`}>
        <ProductList />
        <Suspense fallback="Loading Remote Component...">
          <CartList />
        </Suspense>
      </div>
    </>
  );
}
